version: 2

models:

    - name: sales
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
            
      columns:
          - name: orders_id
            description: one line per product all the column an kpi related to product stock
            tests : 
            - not_null 

          - name: products_id
            description: PK identifier of the product
            tests :
            - not_null
              
          - name: qty

          - name: turnover
            description: line of turnover
            tests : 
            - not_null

          - name: purchase_cost
            description: price of the product
            tests : 
            - not_null

          - name: margin
            description: deifference between purchase_cost and turnover